name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo "REACT_APP_EMAILJS_SERVICE_ID=service_cazlfdx" >> .env
          echo "REACT_APP_EMAILJS_NOTIFICATION_TEMPLATE_ID=template_8gm8c5a" >> .env
          echo "REACT_APP_EMAILJS_AUTOREPLY_TEMPLATE_ID=template_xxpcqid" >> .env
          echo "REACT_APP_EMAILJS_PUBLIC_KEY=fLlukK5veEI51Zr_U" >> .env

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
